---
- name: Clone github
  hosts: localhost
  become: false
  gather_facts: no  # Отключаем сбор фактов
  tasks:
  - name: Ensure /opt/github directory exists
    file:
      path: /tmp/github
      state: directory
      mode: '0755'  # Устанавливаем разрешения для каталога

  - name: Clone the repository
    git:
      repo: 'https://github.com/dRumata/ansible-rh294.ru'
      dest: /tmp/github
      clone: yes
      update: yes  # Обновление репозитория, если он уже существует

- name: Set /etc/hosts
  hosts: lab
  become: true
  gather_facts: no  # Отключаем сбор фактов
  tasks:
  - name: Latest version of all required packages installed
    dnf:
      name:
        - git
        - curl
      state: latest

  - name: Ensure the line is not already present in /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "172.16.195.70 materials.example.com" #ip адрес тренерской машины где будут материалы лежать
      state: present
      create: yes  # Если файл не существует, создать его


- name: Copy content to materials.example.com
  hosts: voitelev
  become: true
  gather_facts: no  # Отключаем сбор фактов
  vars:
    # Заранее определяем массив с парами исходных и целевых путей
    directories_to_copy:
      - { src: "/tmp/github/lab02/deploy-review", dest: "/var/www/html/labs/" }
      - { src: "/tmp/github/lab03/playbook-review", dest: "/var/www/html/labs/" }
      - { src: "/tmp/github/lab04/data-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab05/control-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab06/file-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab07/projects-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab08/role-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab09/troubleshoot-review", dest: "/var/www/html/labs/"}
      - { src: "/tmp/github/lab10/system-review", dest: "/var/www/html/labs/"}

  tasks:
    - name: Latest version of all required packages installed
      dnf:
        name:
          - httpd
        state: latest

    - name: Firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Enable httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: restarted

    - name: Ensure /var/www/html/labs directory exists
      file:
        path: /var/www/html/labs
        state: directory
        mode: '0755'  # Устанавливаем разрешения на каталог

    - name: Ensure the target directories exist
      file:
        path: "{{ item.dest }}"
        state: directory
        mode: '0755'  # Устанавливаем разрешения на каталог
      loop: "{{ directories_to_copy }}"
      # Используем заранее определенный массив с каталогами

    - name: Copy directories to the target locations
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: push  # Синхронизация данных с локального хоста на удаленный
        recursive: yes  # Рекурсивное копирование всех файлов и папок
        delete: no  # Не удаляем файлы в целевой папке, которых нет в исходной
      loop: "{{ directories_to_copy }}"
      # Используем тот же массив для копирования каталогов